### ISSUE TITLE
Obsolete versions of dependency packages not getting deleted [emacs 25.x]

### ISSUE THREAD

**Issue by kaushalmodi** [Bruce-Connor/paradox#47]
Here's an example: I have `helm` installed because I use `helm-swoop`. While the latest versions of `helm` get installed, the older versions are not being deleted.

I am unable to see the "obsolete" marked versions in "emacs -Q" session after updating `package-archives` list to include Melpa. Also the below report is shown in the \*Paradox Report\* buffer so I believe that Paradox is gating the deletion.

If not, let me know if I should file an emacs bug report instead.

> Package transaction finished. Tue 10 Mar 2015 09:32:48 AM EDT
> Errors:
  (error Package `helm-20150308.2341' is used by `helm-swoop' as dependency, not deleting)
(error Package `helm-20150309.619' is used by `helm-swoop' as dependency, not deleting)

> Installed:
  projectile  20150310.522
  helm        20150309.2222

> Deleted:
  projectile  20150301.213

Thanks!

**Comment by Bruce-Connor** [comment]
Paradox, doesn't do any dependency management. So this looks like something in package.el.
I'm guessing you're following Emacs `master`, as this feature was added very recently.
If so, check that you have the latest build.

**Comment by Bruce-Connor** [comment]
> I am unable to see the "obsolete" marked versions in "emacs -Q" 

This is very odd. If there are multiple versions of helm inside your `elpa/` subdir, you should see at least one obsolete item when you call `list-packages` (even without melpa).

**Comment by kaushalmodi** [comment]
My built version was about a week old when I got the above error and I just updated to the latest version as I posted this. I wasn't able to make the `package-list-packages` show the obsolete versions marked with the **obsolete** tags in the emacs -Q session (before I updated). So there was no way for me to delete the old versions from the package manager even though they existed on disk. 

I then removed them manually from the terminal using `\rm -rf`.

I keep a tab on this issue and try to recreate it without `paradox` the next time helm updates.

**Comment by kaushalmodi** [comment]
Helm got an update again and I eval'ed the below in an "emacs -Q" session. [This](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=33d9869b5f7a5acaca838e2b57e5ae713df9603d) is my emacs 25.x build.

```el
(require 'package)
(setq user-home-directory  (getenv "HOME"))
(setq user-emacs-directory (concat user-home-directory "/.emacs.d"))
(setq emacs-version-short  (replace-regexp-in-string
                            "\\([0-9]+\\)\\.\\([0-9]+\\).*"
                            "\\1_\\2" emacs-version)) ; 25.0.50.1 -> 25_0

;; Create the package install directory if it doesn't exist
(setq package-user-dir (concat user-emacs-directory "/elpa_"
                               emacs-version-short)) ; default = ~/.emacs.d/elpa

;; add all sub directories under package install dir to the load-path
(let ((default-directory package-user-dir))
  (normal-top-level-add-subdirs-to-load-path))

;; Add melpa package source when using package list
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
```

Helm updated fine and deleted the old version. Next time I will try updating helm in an emacs -Q session with the above code + `paradox` `require`.

**Comment by Bruce-Connor** [comment]
Alright, keep me posted.

**Comment by kaushalmodi** [comment]
Interesting.. `helm` got updated once again today.

So in an "emacs -Q" session, I added the below to the above snippet
```el
(package-initialize)
(require 'paradox)
(setq paradox-github-token "MY_TOKEN")
```
and then called `M-x paradox-list-packages` and chose to upgrade `helm`.

The same error repeated:

> 
Package transaction finished. Tue 10 Mar 2015 03:30:24 PM EDT
Errors:
  (error Package `helm-20150310.807' is used by `helm-swoop' as dependency, not deleting)

> Installed:
  helm  20150310.1023

**Comment by Bruce-Connor** [comment]
Ok. I'm going to look into this. Maybe paradox is doing something incompatible with the latest package.el version, but it's strange that I don't have this problem.

Was that upgrade synchronous or asynchronous?

**Comment by kaushalmodi** [comment]
asynchronous

**Comment by kaushalmodi** [comment]
Can paradox control the order of installation and deletion? Probably `package.el` installs first and deletes the old version later. Whereas when doing async update in `paradox`, deletion tries to happen before installation?

**Comment by kaushalmodi** [comment]
I'll `edebug` the `package-install` and `package-delete` functions the next time. I am curious to see how `paradox--perform-package-transaction` and the advice in this affects the install and delete order.

**Comment by Bruce-Connor** [comment]
They don't. Paradox installs first and deletes second, just like package.el. 
The issue is probably more subtle.

The advice in there is used to track all calls to `package-activate-1` that happen in the async process, and afterwards reproduce them in the running instance. It's not used at all if the upgrade runs synchronously.

**Comment by Bruce-Connor** [comment]
Next time help updates, could you check if the issue also happens synchronously? (I have a feeling it won't)
This would help narrow down the issue.

**Comment by kaushalmodi** [comment]
OK, will do.

**Comment by Bruce-Connor** [comment]
Also, maybe if you backup your `elpa/` subdir before upgrading helm, you can undo the upgrade afterwards and keep testing without having to wait for helm to update. :)

**Comment by kaushalmodi** [comment]
That's exactly what I had in mind :)

**Comment by kaushalmodi** [comment]
I haven't launched emacs 24.4 in a while so I have fairly old packages lying in my `elpa_24_4/` :)

And you're right, synchronous update doesn't cause a problem:

> Package transaction finished. Tue 10 Mar 2015 04:25:40 PM EDT
Installed:
  helm  20150310.1023

> Deleted:
  helm  20150222.2156

**Comment by Bruce-Connor** [comment]
In the mean time, a few things I've gathered on the subject:

- Dependency checking is done inside `package-delete` by `package--used-elsewhere-p`.
- `package--used-elsewhere-p` always returns nil (which means _“OK to delete”_) if the package is considered obsolete. This is what **should** be happening to `helm`.
- A package is considered obsolete if there's a newer entry on `package-alist` (this test is done in `package-desc-status`).
- `package-install` calls `package-download-transaction` which calls `package-install-from-archive` which calls `package-unpack` which calls `package-load-descriptor` which calls `package-process-define-package` which adds the package to `package-alist`.

One of these things is not working for you. Most likely: either the package is not being seen as obsolete by `package-desc-status`, or it is not being added to `package-alist` in the right place.

Also, if it turns out that your issue only happens asynchronously, then trying to edebug will be essentially useless since the error is happening on another process.

**Comment by Bruce-Connor** [comment]
Ok. I'll give you a snippet to evaluate in a minute.

**Comment by kaushalmodi** [comment]
Any way to see the `message` calls I put in `package-delete` and `package-install`? I realized that those debug statements are useless as those fns are executed asynchronously.

**Comment by Bruce-Connor** [comment]
You could write them to a file instead of messaging.

(btw,  I just managed to reproduce the problem).

**Comment by kaushalmodi** [comment]
Cool! Curious to know all the details. I seem to have a corner-case bug finding emacs setup :P

**Comment by Bruce-Connor** [comment]
Ok, it seems the problem is that we're not injecting the right variables into the async process.

Currently we inject `package-user-dir`, `package-archives`, and `package-archive-contents`, and then let everything else be generated by a call to `package-initialize`. I really thought that should be enough, but it seems I missed something. I replaced the code with something that injects every single `package-` variable, and that fixes the issue (at least for me).

I'll push the fix and you can let me know if it solves your issue too.

**Comment by kaushalmodi** [comment]
Fix confirmed to work. Thanks!
